2024-04-07 15:04:15,474 - INFO - 
Training client 0 model...
2024-04-07 15:04:36,379 - INFO - Epoch 1/3, Loss: 0.7387
2024-04-07 15:04:58,227 - INFO - Epoch 2/3, Loss: 0.3540
2024-04-07 15:05:20,666 - INFO - Epoch 3/3, Loss: 0.2771
2024-04-07 15:05:20,843 - INFO - Training logs saved successfully for client_0 in DB.
2024-04-07 15:05:20,859 - INFO - 
Evaluating client 0 model...
2024-04-07 15:05:25,007 - INFO - Test set: Loss: 0.1639, Accuracy: 0.9495, Precision: 0.9502, Recall: 0.9495, F1: 0.9495
2024-04-07 15:05:25,022 - INFO - Confusion Matrix:
[[ 964    0    1    0    0    3    9    1    2    0]
 [   0 1122    3    2    0    0    5    0    3    0]
 [  11    0  984    8    3    0   10    4   11    1]
 [   0    1   18  958    0   10    2    9    9    3]
 [   0    2    6    0  902    0   24    2    3   43]
 [   6    2    0   20    1  833   17    1    8    4]
 [   7    3    1    2    2    6  937    0    0    0]
 [   5    7   35    6    4    0    0  941    0   30]
 [   6    4    8   18    4   10   16    4  899    5]
 [   8    9    1   14   11    3    2    4    2  955]]
2024-04-07 15:05:25,205 - INFO - Evaluation logs saved successfully for client_0 for round 0 in DB.
2024-04-07 15:05:25,407 - INFO - Client model saved for client_0 in DB.
2024-04-07 15:06:39,547 - INFO - Update for client_0 saved in DB.
FigureCanvasAgg is non-interactive, and thus cannot be shown

FL Training Round 1/1
Traceback (most recent call last):
  File "D:\Rathe\Final Year\FYP\Implementation\NotionFL\notionfl-be\main.py", line 231, in <module>
    main(training_id)
  File "D:\Rathe\Final Year\FYP\Implementation\NotionFL\notionfl-be\main.py", line 97, in main
    data_collector.save_client_model_evaluation(client.client_id, evaluation_text, shap_plot)
  File "D:\Rathe\Final Year\FYP\Implementation\NotionFL\notionfl-be\utils\data_collector.py", line 131, in save_client_model_evaluation
    training_session.save()
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\mongoengine\document.py", line 429, in save
    object_id, created = self._save_update(
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\mongoengine\document.py", line 549, in _save_update
    last_error = wc_collection.update_one(
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\collection.py", line 1086, in update_one
    self._update_retryable(
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\collection.py", line 881, in _update_retryable
    return self.__database.client._retryable_write(
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\mongo_client.py", line 1523, in _retryable_write
    return self._retry_with_session(retryable, func, s, bulk)
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\mongo_client.py", line 1421, in _retry_with_session
    return self._retry_internal(
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\mongo_client.py", line 1462, in _retry_internal
    ).run()
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\mongo_client.py", line 2315, in run
    return self._read() if self._is_read else self._write()
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\mongo_client.py", line 2423, in _write
    return self._func(self._session, conn, self._retryable)  # type: ignore
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\collection.py", line 862, in _update
    return self._update(
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\collection.py", line 816, in _update
    result = conn.command(
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\helpers.py", line 322, in inner
    return func(*args, **kwargs)
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\pool.py", line 996, in command
    self._raise_connection_failure(error)
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\pool.py", line 968, in command
    return command(
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\network.py", line 182, in command
    reply = receive_message(conn, request_id)
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\network.py", line 257, in receive_message
    length, _, response_to, op_code = _UNPACK_HEADER(_receive_data_on_socket(conn, 16, deadline))
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\network.py", line 340, in _receive_data_on_socket
    chunk_length = conn.conn.recv_into(mv[bytes_read:])
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\prash\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
